# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd702d0928abbfd9f57f016cb0f328f48f0856e495f0d42405711198098bee23b328086c057b2d647f8ef20326c9b995d83438c9777a60d2963c130b304cffc4

test:
  secret_key_base: 27451a41f10f4b6ac69aec0afe93b47be6103bbffd24251d7879d0c219d7142da8cbc479c42dfde3373cb48328e710bbed6d087f4c31dc5648b181e523365aa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
